### ISSUE TITLE
Brief

### ISSUE THREAD

**Issue by melkerton** [melkerton/ersatz#34]
### Description:

Ensure all `Endpoint` configs can be developed breadth first and then refined to precise expectations.

i.e.  
1.
```
-  response: DATA
```

2.
```
- path: 1
  response: DATA
```

N.
```
- path: dev-albo-service/protocol/openid-connect/token
  method: POST
  body: grant_type=client_credentials
  response:
      body: '{"access_token": "SERVICE-TOKEN"}'
```
